name: CI/CD to Kubernetes

on:
  push:
    branches:
      - master
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Login DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-udtn:latest .

    - name: Push image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-udtn:latest

    - name: Deploy to Kubernetes (via SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.K8S_MASTER_IP }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_SSH_PRIVATE_KEY }}
        script: |
          cd ~/hello-udtn || git clone https://github.com/duyctytvxdkg/DevOpsBegin.git ~/hello-udtn && cd ~/hello-udtn
          git pull
          sudo kubectl apply -f k8s/deployment-group1.yaml
          sudo kubectl apply -f k8s/deployment-group2.yaml
